### ISSUE TITLE
Minimal Design Object Model

### ISSUE THREAD

**Issue by benlongo** [SoftEngTeamC/FaulknerMap#7]
Create the detailed class diagram for your minimal application. Specify the actual data types you plan to implement, the methods and their signatures. You do not need to create a detailed sequence diagram. However, if you decide to do so, include it in this section

### Class Diagrams
- [x] Directory Data
- [x] Map Data

**Comment by jlcharbonneau** [comment]
[Link to our lucid chart class diagram](https://www.lucidchart.com/invitations/accept/7a037519-df8d-4791-8ab9-e5159ab48044)
